// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/proto/aq/alert.proto

package aq

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------- ALERT PAYLOAD ----------
type AlertPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertType     string                 `protobuf:"bytes,1,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"` // e.g. "HIGH_CO2", "LOW_TEMP"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`              // human-readable text
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp (ms)
	Severity      int32                  `protobuf:"varint,4,opt,name=severity,proto3" json:"severity,omitempty"`                   // e.g. 1=low, 2=medium, 3=critical
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertPayload) Reset() {
	*x = AlertPayload{}
	mi := &file_internal_proto_aq_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertPayload) ProtoMessage() {}

func (x *AlertPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_aq_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertPayload.ProtoReflect.Descriptor instead.
func (*AlertPayload) Descriptor() ([]byte, []int) {
	return file_internal_proto_aq_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AlertPayload) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *AlertPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AlertPayload) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

var File_internal_proto_aq_alert_proto protoreflect.FileDescriptor

const File_internal_proto_aq_alert_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/aq/alert.proto\x12\x02aq\"\x89\x01\n" +
	"\fAlertPayload\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x01 \x01(\tR\talertType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\x05R\bseverityB\x1fZ\x1dIotProto/internal/proto/aq;aqb\x06proto3"

var (
	file_internal_proto_aq_alert_proto_rawDescOnce sync.Once
	file_internal_proto_aq_alert_proto_rawDescData []byte
)

func file_internal_proto_aq_alert_proto_rawDescGZIP() []byte {
	file_internal_proto_aq_alert_proto_rawDescOnce.Do(func() {
		file_internal_proto_aq_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(File_internal_proto_aq_alert_proto_rawDesc), len(File_internal_proto_aq_alert_proto_rawDesc)))
	})
	return file_internal_proto_aq_alert_proto_rawDescData
}

var file_internal_proto_aq_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_aq_alert_proto_goTypes = []any{
	(*AlertPayload)(nil), // 0: aq.AlertPayload
}
var file_internal_proto_aq_alert_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_aq_alert_proto_init() }
func file_internal_proto_aq_alert_proto_init() {
	if File_internal_proto_aq_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(File_internal_proto_aq_alert_proto_rawDesc), len(File_internal_proto_aq_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_aq_alert_proto_goTypes,
		DependencyIndexes: file_internal_proto_aq_alert_proto_depIdxs,
		MessageInfos:      file_internal_proto_aq_alert_proto_msgTypes,
	}.Build()
	File_internal_proto_aq_alert_proto = out.File
	file_internal_proto_aq_alert_proto_goTypes = nil
	file_internal_proto_aq_alert_proto_depIdxs = nil
}
