// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/proto/aq/commonwrapper.proto

package aq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"` // For storing encoded data
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonWrapper) Reset() {
	*x = CommonWrapper{}
	mi := &file_internal_proto_aq_commonwrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonWrapper) ProtoMessage() {}

func (x *CommonWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_aq_commonwrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonWrapper.ProtoReflect.Descriptor instead.
func (*CommonWrapper) Descriptor() ([]byte, []int) {
	return file_internal_proto_aq_commonwrapper_proto_rawDescGZIP(), []int{0}
}

func (x *CommonWrapper) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CommonWrapper) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *CommonWrapper) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_proto_aq_commonwrapper_proto protoreflect.FileDescriptor

const file_internal_proto_aq_commonwrapper_proto_rawDesc = "" +
	"\n" +
	"%internal/proto/aq/commonwrapper.proto\x12\x02aq\"g\n" +
	"\rCommonWrapper\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB\x1fZ\x1dIotProto/internal/proto/aq;aqb\x06proto3"

var (
	file_internal_proto_aq_commonwrapper_proto_rawDescOnce sync.Once
	file_internal_proto_aq_commonwrapper_proto_rawDescData []byte
)

func file_internal_proto_aq_commonwrapper_proto_rawDescGZIP() []byte {
	file_internal_proto_aq_commonwrapper_proto_rawDescOnce.Do(func() {
		file_internal_proto_aq_commonwrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_aq_commonwrapper_proto_rawDesc), len(file_internal_proto_aq_commonwrapper_proto_rawDesc)))
	})
	return file_internal_proto_aq_commonwrapper_proto_rawDescData
}

var file_internal_proto_aq_commonwrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_aq_commonwrapper_proto_goTypes = []any{
	(*CommonWrapper)(nil), // 0: aq.CommonWrapper
}
var file_internal_proto_aq_commonwrapper_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_aq_commonwrapper_proto_init() }
func file_internal_proto_aq_commonwrapper_proto_init() {
	if File_internal_proto_aq_commonwrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_aq_commonwrapper_proto_rawDesc), len(file_internal_proto_aq_commonwrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_aq_commonwrapper_proto_goTypes,
		DependencyIndexes: file_internal_proto_aq_commonwrapper_proto_depIdxs,
		MessageInfos:      file_internal_proto_aq_commonwrapper_proto_msgTypes,
	}.Build()
	File_internal_proto_aq_commonwrapper_proto = out.File
	file_internal_proto_aq_commonwrapper_proto_goTypes = nil
	file_internal_proto_aq_commonwrapper_proto_depIdxs = nil
}
