// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/proto/aq/sensor.proto

package aq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic telemetry message
type SensorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param_1       float64                `protobuf:"fixed64,1,opt,name=param_1,json=param1,proto3" json:"param_1,omitempty"`
	Param_2       float64                `protobuf:"fixed64,2,opt,name=param_2,json=param2,proto3" json:"param_2,omitempty"`
	Param_3       float64                `protobuf:"fixed64,3,opt,name=param_3,json=param3,proto3" json:"param_3,omitempty"`
	Param_4       float64                `protobuf:"fixed64,4,opt,name=param_4,json=param4,proto3" json:"param_4,omitempty"`
	Param_5       float64                `protobuf:"fixed64,5,opt,name=param_5,json=param5,proto3" json:"param_5,omitempty"`
	Param_6       float64                `protobuf:"fixed64,6,opt,name=param_6,json=param6,proto3" json:"param_6,omitempty"`
	Param_7       float64                `protobuf:"fixed64,7,opt,name=param_7,json=param7,proto3" json:"param_7,omitempty"`
	Param_8       float64                `protobuf:"fixed64,8,opt,name=param_8,json=param8,proto3" json:"param_8,omitempty"`
	Param_9       float64                `protobuf:"fixed64,9,opt,name=param_9,json=param9,proto3" json:"param_9,omitempty"`
	Param_10      float64                `protobuf:"fixed64,10,opt,name=param_10,json=param10,proto3" json:"param_10,omitempty"`
	Timestamp     int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorPayload) Reset() {
	*x = SensorPayload{}
	mi := &file_internal_proto_aq_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorPayload) ProtoMessage() {}

func (x *SensorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_aq_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorPayload.ProtoReflect.Descriptor instead.
func (*SensorPayload) Descriptor() ([]byte, []int) {
	return file_internal_proto_aq_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorPayload) GetParam_1() float64 {
	if x != nil {
		return x.Param_1
	}
	return 0
}

func (x *SensorPayload) GetParam_2() float64 {
	if x != nil {
		return x.Param_2
	}
	return 0
}

func (x *SensorPayload) GetParam_3() float64 {
	if x != nil {
		return x.Param_3
	}
	return 0
}

func (x *SensorPayload) GetParam_4() float64 {
	if x != nil {
		return x.Param_4
	}
	return 0
}

func (x *SensorPayload) GetParam_5() float64 {
	if x != nil {
		return x.Param_5
	}
	return 0
}

func (x *SensorPayload) GetParam_6() float64 {
	if x != nil {
		return x.Param_6
	}
	return 0
}

func (x *SensorPayload) GetParam_7() float64 {
	if x != nil {
		return x.Param_7
	}
	return 0
}

func (x *SensorPayload) GetParam_8() float64 {
	if x != nil {
		return x.Param_8
	}
	return 0
}

func (x *SensorPayload) GetParam_9() float64 {
	if x != nil {
		return x.Param_9
	}
	return 0
}

func (x *SensorPayload) GetParam_10() float64 {
	if x != nil {
		return x.Param_10
	}
	return 0
}

func (x *SensorPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_proto_aq_sensor_proto protoreflect.FileDescriptor

const File_internal_proto_aq_sensor_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/aq/sensor.proto\x12\x02aq\"\xa9\x02\n" +
	"\rSensorPayload\x12\x17\n" +
	"\aparam_1\x18\x01 \x01(\x01R\x06param1\x12\x17\n" +
	"\aparam_2\x18\x02 \x01(\x01R\x06param2\x12\x17\n" +
	"\aparam_3\x18\x03 \x01(\x01R\x06param3\x12\x17\n" +
	"\aparam_4\x18\x04 \x01(\x01R\x06param4\x12\x17\n" +
	"\aparam_5\x18\x05 \x01(\x01R\x06param5\x12\x17\n" +
	"\aparam_6\x18\x06 \x01(\x01R\x06param6\x12\x17\n" +
	"\aparam_7\x18\a \x01(\x01R\x06param7\x12\x17\n" +
	"\aparam_8\x18\b \x01(\x01R\x06param8\x12\x17\n" +
	"\aparam_9\x18\t \x01(\x01R\x06param9\x12\x19\n" +
	"\bparam_10\x18\n" +
	" \x01(\x01R\aparam10\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestampB\x1fZ\x1dIotProto/internal/proto/aq;aqb\x06proto3"

var (
	file_internal_proto_aq_sensor_proto_rawDescOnce sync.Once
	file_internal_proto_aq_sensor_proto_rawDescData []byte
)

func file_internal_proto_aq_sensor_proto_rawDescGZIP() []byte {
	file_internal_proto_aq_sensor_proto_rawDescOnce.Do(func() {
		file_internal_proto_aq_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(File_internal_proto_aq_sensor_proto_rawDesc), len(File_internal_proto_aq_sensor_proto_rawDesc)))
	})
	return file_internal_proto_aq_sensor_proto_rawDescData
}

var file_internal_proto_aq_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_aq_sensor_proto_goTypes = []any{
	(*SensorPayload)(nil), // 0: aq.SensorPayload
}
var file_internal_proto_aq_sensor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_aq_sensor_proto_init() }
func file_internal_proto_aq_sensor_proto_init() {
	if File_internal_proto_aq_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(File_internal_proto_aq_sensor_proto_rawDesc), len(File_internal_proto_aq_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_aq_sensor_proto_goTypes,
		DependencyIndexes: file_internal_proto_aq_sensor_proto_depIdxs,
		MessageInfos:      file_internal_proto_aq_sensor_proto_msgTypes,
	}.Build()
	File_internal_proto_aq_sensor_proto = out.File
	file_internal_proto_aq_sensor_proto_goTypes = nil
	file_internal_proto_aq_sensor_proto_depIdxs = nil
}
